export const eventData =
[
    {
        "id": 1,
        "name": "Food Drive",
        "administrator": "John Doe",
        "description": "Organize and distribute food items to those in need.",
        "address": "2 N. Cross Street",
        "city": "Hernando",
        "state": "Alabama",
        "zip": "38632",
        "date": "02/05/2024",
        "time": "4:00 PM",
        "duration": "3h 30m",
        "skills": "Mobility Assistance, Initiative, Ability to Work in Various Weather Conditions",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 2,
        "name": "Beach Cleanup",
        "administrator": "Jane Smith",
        "description": "Clean up local beaches to keep our environment clean.",
        "address": "8469 York Street",
        "city": "Bakersfield",
        "state": "Alaska",
        "zip": "93306",
        "date": "03/20/2024",
        "time": "9:45 AM",
        "duration": "3h 30m",
        "skills": "Good Vision, Physical Therapy Skills, Critical Thinking",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 3,
        "name": "Health Fair",
        "administrator": "Robert Johnson",
        "description": "Host a health fair to educate the community about wellness.",
        "address": "7753 Henry Smith Ave.",
        "city": "Erlanger",
        "state": "Arizona",
        "zip": "41018",
        "date": "04/10/2024",
        "time": "12:45 PM",
        "duration": "3h 45m",
        "skills": "Patience, Resilience, Flexibility",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 4,
        "name": "Tree Planting",
        "administrator": "Emily Williams",
        "description": "Plant trees in local parks to combat deforestation.",
        "address": "696 W. Lake View Street",
        "city": "Northbrook",
        "state": "Arkansas",
        "zip": "60062",
        "date": "05/25/2024",
        "time": "3:45 PM",
        "duration": "3h 0m",
        "skills": "Basic First Aid, Empathy, First Aid/CPR Certification",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 5,
        "name": "Habitat Restoration",
        "administrator": "Michael Brown",
        "description": "Restore habitats damaged by natural disasters.",
        "address": "18 Glendale Rd.",
        "city": "Saint Albans",
        "state": "California",
        "zip": "11412",
        "date": "06/15/2024",
        "time": "2:00 PM",
        "duration": "2h 45m",
        "skills": "Physical Stamina, Able to Lift 50 lbs, Teamwork",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 6,
        "name": "Art Workshop",
        "administrator": "Jessica Davis",
        "description": "Create art workshops to foster creativity among volunteers.",
        "address": "219 North Lakewood Lane",
        "city": "Wisconsin Rapids",
        "state": "Colorado",
        "zip": "54494",
        "date": "07/30/2024",
        "time": "9:00 AM",
        "duration": "4h 0m",
        "skills": "Empathy, Sign Language Interpretation, Coordination",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 7,
        "name": "Tech Recycling",
        "administrator": "Richard Miller",
        "description": "Recycle old tech devices responsibly.",
        "address": "516 Newcastle Lane",
        "city": "Fort Lauderdale",
        "state": "Connecticut",
        "zip": "33308",
        "date": "08/20/2024",
        "time": "7:00 PM",
        "duration": "2h 45m",
        "skills": "Good Vision, Adaptability, Flexibility",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 8,
        "name": "Community Garden",
        "administrator": "Patricia Moore",
        "description": "Maintain and grow community gardens.",
        "address": "455 Pineknoll Ave.",
        "city": "Far Rockaway",
        "state": "Delaware",
        "zip": "11691",
        "date": "09/05/2024",
        "time": "4:30 PM",
        "duration": "2h 30m",
        "skills": "Technical Proficiency, Able to Lift 50 lbs, Creativity",
        "urgency": "Critical",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 9,
        "name": "Homeless Shelter",
        "administrator": "Charles Jackson",
        "description": "Provide shelter and support to homeless individuals.",
        "address": "8827 East Blue Spring Lane",
        "city": "Gallatin",
        "state": "District Of Columbia",
        "zip": "37066",
        "date": "10/20/2024",
        "time": "11:00 AM",
        "duration": "4h 45m",
        "skills": "Ability to Work Standing/Walking for Long Periods, Wheelchair Assistance, Empathy",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 10,
        "name": "Pet Adoption Day",
        "administrator": "Michelle Taylor",
        "description": "Find loving homes for animals in shelters.",
        "address": "9614 N. Sycamore Dr.",
        "city": "Oconomowoc",
        "state": "Florida",
        "zip": "53066",
        "date": "11/15/2024",
        "time": "6:30 PM",
        "duration": "2h 15m",
        "skills": "Flexibility, Time Management, Coordination",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 11,
        "name": "Wildlife Conservation",
        "administrator": "David Wilson",
        "description": "Conserve wildlife populations through conservation efforts.",
        "address": "7356 Glenholme Ave.",
        "city": "Miami",
        "state": "Georgia",
        "zip": "33125",
        "date": "12/30/2024",
        "time": "11:00 AM",
        "duration": "1h 45m",
        "skills": "Patience, Flexibility, Good Vision",
        "urgency": "Critical",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 12,
        "name": "Book Drive",
        "administrator": "Linda Anderson",
        "description": "Collect books for educational purposes.",
        "address": "9360 Roehampton Lane",
        "city": "Everett",
        "state": "Hawaii",
        "zip": "02149",
        "date": "01/25/2025",
        "time": "7:00 PM",
        "duration": "5h 15m",
        "skills": "Creativity, Listening, Problem-Solving",
        "urgency": "Critical",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 13,
        "name": "Sustainable Living Workshop",
        "administrator": "Mark Thomas",
        "description": "Educate the public on sustainable living practices.",
        "address": "367 Railroad St.",
        "city": "Lumberton",
        "state": "Idaho",
        "zip": "28358",
        "date": "02/15/2025",
        "time": "3:15 PM",
        "duration": "1h 15m",
        "skills": "Endurance, Computer Literacy, Ability to Work in Various Weather Conditions",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 14,
        "name": "Mental Health Awareness",
        "administrator": "Jennifer White",
        "description": "Raise awareness about mental health issues.",
        "address": "658 Pierce St.",
        "city": "Edison",
        "state": "Illinois",
        "zip": "08817",
        "date": "03/30/2025",
        "time": "2:15 PM",
        "duration": "0h 45m",
        "skills": "First Aid/CPR Certification, Basic First Aid, Coordination",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 15,
        "name": "Environmental Education",
        "administrator": "Daniel Martin",
        "description": "Educate students about environmental science.",
        "address": "65 Squaw Creek St.",
        "city": "Orlando",
        "state": "Indiana",
        "zip": "32806",
        "date": "04/20/2025",
        "time": "1:30 PM",
        "duration": "2h 0m",
        "skills": "Coordination, First Aid/CPR Certification, Resilience",
        "urgency": "High",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 16,
        "name": "Sports Tournament",
        "administrator": "Karen Lee",
        "description": "Organize sports tournaments to promote physical activity.",
        "address": "137 Beechwood St.",
        "city": "Cleveland",
        "state": "Iowa",
        "zip": "37312",
        "date": "05/25/2025",
        "time": "6:15 PM",
        "duration": "1h 15m",
        "skills": "Flexibility, Physical Therapy Skills, Wheelchair Assistance",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 17,
        "name": "Music Festival",
        "administrator": "Matthew Green",
        "description": "Celebrate music and culture through a festival.",
        "address": "8 South Nut Swamp St.",
        "city": "El Paso",
        "state": "Kansas",
        "zip": "79930",
        "date": "06/15/2025",
        "time": "9:15 AM",
        "duration": "6h 0m",
        "skills": "Physical Therapy Skills, Ability to Work Standing/Walking for Long Periods, First Aid/CPR Certification",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 18,
        "name": "Cultural Exchange",
        "administrator": "Nancy Harris",
        "description": "Exchange cultural experiences between different communities.",
        "address": "378 Elizabeth Avenue",
        "city": "Hartford",
        "state": "Kentucky",
        "zip": "06106",
        "date": "07/30/2025",
        "time": "1:15 PM",
        "duration": "2h 0m",
        "skills": "Time Management, Able to Lift 50 lbs, Flexibility",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 19,
        "name": "STEM Camp",
        "administrator": "Donald Thompson",
        "description": "Offer STEM education and hands-on projects for youth.",
        "address": "8177 W. Euclid St.",
        "city": "Thornton",
        "state": "Louisiana",
        "zip": "80241",
        "date": "08/20/2025",
        "time": "5:00 PM",
        "duration": "3h 15m",
        "skills": "Sign Language Interpretation, Good Vision",
        "urgency": "Low",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 20,
        "name": "Farmers Market",
        "administrator": "Betty Clark",
        "description": "Sell locally grown produce and crafts at a farmers market.",
        "address": "73 South Somerset St.",
        "city": "Brighton",
        "state": "Maine",
        "zip": "02135",
        "date": "09/05/2025",
        "time": "1:00 PM",
        "duration": "3h 15m",
        "skills": "Listening, Physical Therapy Skills, Good Hearing",
        "urgency": "Critical",
        "volunteers": 0,
        "creator": 2,
    },
    {
        "id": 21,
        "name": "Craft Fair",
        "administrator": "George Rodriguez",
        "description": "Display and sell handmade crafts to support local artisans.",
        "address": "690 Trout Ave.",
        "city": "Fleming Island",
        "state": "Maryland",
        "zip": "32003",
        "date": "10/20/2025",
        "time": "2:15 PM",
        "duration": "5h 0m",
        "skills": "Coordination, Technical Proficiency, Adaptability",
        "urgency": "Medium",
        "volunteers": 0,
        "creator": 2,
    }
]