import React from 'react'

export const skillsData = [
    "Communication",
    "Teamwork",
    "Problem-Solving",
    "Organizational Skills",
    "Time Management",
    "Flexibility",
    "Adaptability",
    "Empathy",
    "Patience",
    "Attention to Detail",
    "Creativity",
    "Leadership",
    "Initiative",
    "Resilience",
    "Motivation",
    "Listening",
    "Critical Thinking",
    "Technical Proficiency",
    "Computer Literacy",
    "Basic First Aid",
    "Physical Stamina",
    "Strength",
    "Endurance",
    "Coordination",
    "Manual Dexterity",
    "Able to Lift 50 lbs",
    "Ability to Work Standing/Walking for Long Periods",
    "Good Hearing",
    "Good Vision",
    "Ability to Work in Various Weather Conditions",
    "Physical Therapy Skills",
    "Occupational Therapy Skills",
    "Speech-Language Pathology Skills",
    "Sign Language Interpretation",
    "Wheelchair Assistance",
    "Mobility Assistance",
    "First Aid/CPR Certification",
    "Emergency Response Training"
];