# Generated by Django 5.0.6 on 2024-07-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Duration',
            field=models.CharField(default='3h 0m', max_length=6),
        ),
    ]
