# Generated by Django 5.0.6 on 2024-06-17 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.CharField(default='', max_length=10, unique=True)),
                ('Administrator', models.CharField(max_length=50)),
                ('Urgency', models.CharField(default='', max_length=10)),
                ('Address', models.CharField(max_length=75)),
                ('State', models.CharField(max_length=2)),
                ('City', models.CharField(max_length=45)),
                ('Zip_Code', models.CharField(max_length=10)),
                ('Volunteer_Count', models.IntegerField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='Skills',
            field=models.ManyToManyField(related_name='events', to='api.skill'),
        ),
    ]
