# Generated by Django 5.0.6 on 2024-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Volunteer_Count',
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.CharField(default='07/16/2024', max_length=10),
        ),
    ]
