# Generated by Django 5.0.6 on 2024-07-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_matched_notification_states_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.CharField(default='2024/23/07', max_length=10),
        ),
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
