# Generated by Django 5.0.6 on 2024-06-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_skill_delete_room_event_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='Event_ID',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
