# Generated by Django 5.0.6 on 2024-07-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_event_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.CharField(max_length=10, unique=True)),
                ('Volunteer', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.CharField(default='2024/18/07', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='event_volunteers',
            constraint=models.UniqueConstraint(fields=('Event_ID', 'Volunteer'), name='unique_event_volunteer'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
