# Generated by Django 5.0.6 on 2024-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_event_volunteers_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.CharField(default='2024/21/07', max_length=10),
        ),
    ]
