# Generated by Django 5.0.6 on 2024-07-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.CharField(max_length=10)),
                ('Volunteer', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.UniqueConstraint(fields=('Event_ID', 'Volunteer'), name='unique_event_volunteers'),
        ),
    ]
