# Generated by Django 5.0.6 on 2024-07-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_test_test_unique_event_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Update_Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_ID', models.CharField(max_length=10)),
                ('Volunteer', models.CharField(max_length=30)),
            ],
        ),
    ]
