# Generated by Django 5.0.6 on 2024-07-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_update_volunteers_delete_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_volunteers',
            name='Attended',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
